### ISSUE TITLE
Issue in selected bottom nav on back button click

### ISSUE THREAD

**Issue by gunjchhetri** [jeaanlucas/circle_bottom_navigation#1]
Hi,
I have three screens- Home, History and Notification, where each screen has it own scaffold with its own BottomNavBar.
The issue I am getting here is that the selected Nav menu remain same, whereas screen changes to other screen, when I click back button.

Could you please have a look at this?

**Comment by jeaanlucas** [comment]
Hello @gunjchhetri 

Maybe is because you implemented it wrong. When you have three scaffolds and three navbars, the navbars doesn't share the state of each one, so, each one will stay the same.
You need to implement the navbar on a unique scaffold and inject the content on his body, like this:

```
int currentPage = 0;

final _pageOptions = [
    Widget1(),
    Widget2(),
    Widget3(),
  ];

Scaffold(
        body: _pageOptions[currentPage],
        bottomNavigationBar: CircleBottomNavigation(
          initialSelection: routePage.currentPage,
          inactiveIconColor: Colors.grey,
          textColor: Colors.black,
          hasElevationShadows: false,
          tabs: [
            TabData(
              icon: Icon,
              title: 'Widget1',
            ),
            TabData(
              icon: Icon,
              title: 'Widget2',
            ),
            TabData(
              icon: Icon,
              title: 'Widget3',
            ),
          ],
          onTabChangedListener: (index) => setState(() => currentPage = index),
        ),
      )
```

**Comment by jeaanlucas** [comment]
@gunjchhetri your problem is solved? 
Can i close this issue?
