### ISSUE TITLE
programmatically select Bottom Navigation Bar Tab instead of built in onTabChangedListener

### ISSUE THREAD

**Issue by aashish-shirgave** [jeaanlucas/circle_bottom_navigation#2]
We cannot change the state of the bottom navigation without onTabChangedListener callback
Can we access the state of the bar programmatically ??

**Comment by jeaanlucas** [comment]
Hi, the state management of onTabChangedListener is for change all the screens. Inside a screen you can work with your state management separately.
Whatever, fell free to open a PR with enhancements :D
