### ISSUE TITLE
package does not have null safety support yet

### ISSUE THREAD

**Issue by alceil** [jeaanlucas/circle_bottom_navigation#5]
Hey,
The package you created is amazing because of you I have been able to use amazing bottom navigation UI in my app.
But I would like to request you that the package doesn't have null safety support yet.
I would like you to add null safety support .
Thank you
Your sincerely 
Ashish tom

**Comment by jeaanlucas** [comment]
Hello, thanks for your support :D
At this moment, i don't have time to do this. 
Feel free to open a PR :D
Thanks.

**Comment by alceil** [comment]
I have added null safety support to this package. Can you accept my pull request
https://github.com/jeaanlucas/circle_bottom_navigation/pull/6#issue-684543891
